[workspace]
members = [
    "zkcasper-circuits",
    "preprocessor",
    "eth-types",
    "gadgets",
]

# [patch."https://github.com/privacy-scaling-explorations/halo2.git"]
# halo2_proofs = { git = "https://github.com/scroll-tech/halo2.git", branch = "scroll-dev-0220" }

# [patch."https://github.com/privacy-scaling-explorations/zkevm-circuits.git"]
# eth-types = { path = "./eth-types" }


# Definition of benchmarks profile to use.
[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
rpath = false
lto = "thin"
incremental = false
codegen-units = 1

[profile.release]
opt-level = 3
debug = false
debug-assertions = true
overflow-checks = true
rpath = false
lto = "thin"
incremental = true

[patch."https://github.com/privacy-scaling-explorations/halo2curves"]
halo2curves = { git = "https://github.com/timoftime/halo2curves", branch = "zkcasper" }

[patch."https://github.com/axiom-crypto/halo2-lib"]
halo2-base = { git = "https://github.com/timoftime/halo2-lib", branch = "zkcasper", default-features = false, features = [
    "halo2-pse",
    "display",
] }
halo2-ecc = { git = "https://github.com/timoftime/halo2-lib", branch = "zkcasper", default-features = false }
