name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CI: 1
  CARGO_INCREMENTAL: 1

jobs:
  license:
    name: check-license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          override: true
    - name: Install licensesnip
      uses: baptiste0928/cargo-install@v2
      with:
        crate: licensesnip
        locked: true
    - name: Run licensesnip
      run: licensesnip check

  test:
    name: build-and-test
    runs-on: buildjet-8vcpu-ubuntu-2204
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          override: true
          components: rustfmt
    - name: Check
      run: cargo check --all
